# Generated by Django 4.2.2 on 2023-06-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filemanager", "0003_rename_purchaseorder_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("sender", models.CharField(max_length=100, null=True)),
                ("receiver", models.CharField(max_length=100, null=True)),
                (
                    "purchaseOrderNumber",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
