# Generated by Django 4.2.2 on 2023-06-19 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filemanager", "0004_purchaseorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="date",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="sender",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="purchaseOrderNumber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="filemanager.purchaseorder",
            ),
        ),
    ]
