# Generated by Django 4.2.2 on 2023-06-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filemanager", "0007_invoice_date_invoice_receiver_invoice_sender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="edi_type",
            field=models.CharField(default="850"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="edi_type",
            field=models.CharField(default="850"),
        ),
    ]
