# Generated by Django 4.2.2 on 2023-06-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filemanager", "0008_invoice_edi_type_purchaseorder_edi_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="edi_type",
            field=models.CharField(default="810"),
        ),
    ]
